- name: (agent5) Create Datadog agent config directory
  when: datadog_manage_config
  ansible.builtin.file:
    dest: /etc/dd-agent
    state: directory
    mode: 493
- name: (agent5) Create main Datadog agent configuration file
  when: datadog_manage_config
  notify: restart datadog-agent
  ansible.builtin.template:
    src: datadog.conf.j2
    dest: /etc/dd-agent/datadog.conf
    owner: '{{ datadog_user }}'
    group: '{{ datadog_group }}'
    mode: 420
- name: (agent5) Ensure datadog-agent is running
  when: not datadog_skip_running_check and datadog_enabled and not ansible_check_mode
  ansible.builtin.service:
    name: datadog-agent
    state: started
    enabled: true
- name: (agent5) Ensure datadog-agent is not running
  when: not datadog_skip_running_check and not datadog_enabled
  ansible.builtin.service:
    name: datadog-agent
    state: stopped
    enabled: false
- name: Register all checks files present in datadog
  register: datadog_conf_files
  when: datadog_manage_config and datadog_disable_untracked_checks
  ansible.builtin.find:
    paths: /etc/dd-agent/conf.d/
    patterns:
    - '*.yaml'
    file_type: file
- name: Register all checks files present in datadog
  register: datadog_conf_files_default
  when: datadog_manage_config and datadog_disable_default_checks
  ansible.builtin.find:
    paths: /etc/dd-agent/conf.d/
    patterns:
    - '*.yaml.default'
    file_type: file
- name: Delete checks not present in datadog_tracked_checks
  loop: '{{ datadog_conf_files.files | map(attribute=''path'') | list | map(''basename'')
    | list | map(''regex_replace'', ''^(.*).yaml$'', ''\1'') | list }}'
  when: datadog_manage_config and datadog_disable_untracked_checks and item not in
    datadog_tracked_checks
  notify: restart datadog-agent
  ansible.builtin.file:
    path: /etc/dd-agent/conf.d/{{ item }}.yaml
    state: absent
- name: Delete default checks
  loop: '{{ datadog_conf_files_default.files | map(attribute=''path'') | list | map(''basename'')
    | list | map(''regex_replace'', ''^(.*).yaml.default$'', ''\1'') | list }}'
  when: datadog_manage_config and datadog_disable_default_checks and item not in datadog_tracked_checks
  notify: restart datadog-agent
  ansible.builtin.file:
    path: /etc/dd-agent/conf.d/{{ item }}.yaml.default
    state: absent
- name: (agent5) Create a configuration file for each Datadog check
  with_items: '{{ datadog_checks|list }}'
  when: datadog_manage_config
  notify: restart datadog-agent
  ansible.builtin.template:
    src: checks.yaml.j2
    dest: /etc/dd-agent/conf.d/{{ item }}.yaml
    owner: '{{ datadog_user }}'
    group: '{{ datadog_group }}'
    mode: 420
