- name: Validate integrations actions
  when: item.value.action != "install" and item.value.action != "remove"
  loop: '{{ datadog_integration|dict2items }}'
  ansible.builtin.fail:
    msg: Unkown action '{{ item.value.action }}' for integration command ({{ item.key
      }}). Valid actions are 'install' and 'remove'
- name: Include Windows Integration Tasks
  when: ansible_facts.os_family == "Windows"
  ansible.builtin.include_tasks: integration/windows.yml
- name: Include macOS Integration Tasks
  when: ansible_facts.os_family == "Darwin"
  ansible.builtin.include_tasks: integration/macos.yml
- name: Include Linux Integration Tasks
  when: ansible_facts.os_family != "Darwin" and ansible_facts.os_family != "Windows"
  ansible.builtin.include_tasks: integration/linux.yml
