- name: Include Gather Ansible Facts task on Ansible >= 2.10
  when: ansible_version.major >= 2 and ansible_version.minor >= 10
  ansible.builtin.include_tasks: facts-ansible10.yml
- name: Include Gather Ansible Facts task on Ansible < 2.10
  when: ansible_version.major == 2 and ansible_version.minor < 10
  ansible.builtin.include_tasks: facts-ansible9.yml
- name: Check if OS is supported
  ansible.builtin.include_tasks: os-check.yml
- name: Resolve datadog_tracked_checks later to defend against variable presidence
    issues arising from dynamically included null datadog_checks
  ansible.builtin.include_tasks: sanitize-checks.yml
- name: Set Facts for Datadog Agent Major Version
  ansible.builtin.include_tasks: set-parse-version.yml
- name: Debian Install Tasks
  when: ansible_facts.os_family == "Debian" and not datadog_skip_install
  ansible.builtin.include_tasks: pkg-debian.yml
- name: Include tasks to remove old GPG keys
  when: ansible_facts.os_family in ["RedHat", "Rocky", "AlmaLinux", "Suse"]
  loop: '{{ datadog_rpm_remove_keys }}'
  ansible.builtin.include_tasks: _remove_rpm_keys.yml
- name: Include tasks to check removed configuration value usage
  ansible.builtin.include_tasks: check-removed-config.yml
- name: RedHat Install Tasks
  when: ansible_facts.os_family in ["RedHat", "Rocky", "AlmaLinux"] and not datadog_skip_install
  ansible.builtin.include_tasks: pkg-redhat.yml
- name: Suse Install Tasks
  when: ansible_facts.os_family == "Suse" and not datadog_skip_install
  ansible.builtin.include_tasks: pkg-suse.yml
- name: Windows Install Tasks
  when: ansible_facts.os_family == "Windows"
  ansible.builtin.include_tasks: pkg-windows.yml
- name: macOS Install Tasks
  when: ansible_facts.os_family == "Darwin" and not datadog_skip_install
  ansible.builtin.include_tasks: pkg-macos.yml
- name: Linux Configuration Tasks (Agent 5)
  when: datadog_agent_major_version | int == 5 and ansible_facts.os_family != "Windows"  and
    ansible_facts.os_family != "Darwin"
  ansible.builtin.include_tasks: agent5-linux.yml
- name: Linux Configuration Tasks
  when: datadog_agent_major_version | int > 5 and ansible_facts.os_family != "Windows"
    and ansible_facts.os_family != "Darwin"
  ansible.builtin.include_tasks: agent-linux.yml
- name: Windows Configuration Tasks
  when: datadog_agent_major_version | int > 5 and ansible_facts.os_family == "Windows"
  ansible.builtin.include_tasks: agent-win.yml
- name: macOS Configuration Tasks
  when: ansible_facts.os_family == "Darwin"
  ansible.builtin.include_tasks: agent-macos.yml
- name: Integrations Tasks
  when: datadog_integration is defined
  ansible.builtin.include_tasks: integration.yml
