- name: Fail if Agent 5
  when: datadog_agent_major_version|int == 5
  ansible.builtin.fail:
    msg: The Datadog ansible role does not currently support Agent 5
- name: Download windows datadog agent 614 fix script
  when: not datadog_skip_install and datadog_apply_windows_614_fix
  ansible.windows.win_get_url:
    url: '{{ datadog_windows_614_fix_script_url }}'
    dest: '%TEMP%\fix_6_14.ps1'
- name: Run 6.14.0/1 PowerShell fix
  when: not datadog_skip_install and datadog_apply_windows_614_fix
  ansible.windows.win_shell: 'Set-ExecutionPolicy Bypass -Scope Process -Force

    &$env:temp\fix_6_14.ps1

    '
- when: (not datadog_skip_install) and (datadog_agent_windows_version is not defined)
  ansible.builtin.include_tasks: win_agent_latest.yml
- when: (not datadog_skip_install) and (datadog_agent_windows_version is defined)
  ansible.builtin.include_tasks: win_agent_version.yml
- name: show URL var
  when: not datadog_skip_install
  ansible.builtin.debug:
    var: dd_download_url
- name: Set windows NPM installed
  ansible.builtin.set_fact:
    datadog_sysprobe_enabled: '{{ network_config is defined and ''enabled'' in (network_config
      | default({}, true)) and network_config[''enabled''] }}'
- ansible.builtin.include_tasks: pkg-windows-opts.yml
- name: pre-Delete temporary msi
  when: not datadog_skip_install
  ansible.windows.win_file:
    path: '%TEMP%\ddagent.msi'
    state: absent
- name: Download windows datadog agent
  register: download_msi_result
  when: (not datadog_skip_install) and (not ansible_check_mode)
  ansible.windows.win_get_url:
    url: '{{ dd_download_url }}'
    dest: '%TEMP%\ddagent.msi'
- name: Create Binary directory root (if not default)
  when: datadog_windows_program_files_dir | length > 0
  ansible.windows.win_file:
    path: '{{ datadog_windows_program_files_dir }}'
    state: directory
- name: Set default permissions on binary directory root (if not default)
  when: datadog_windows_program_files_dir | length > 0
  ansible.windows.win_acl:
    path: '{{ datadog_windows_program_files_dir }}'
    inherit: ContainerInherit,ObjectInherit
    user: BUILTIN\USERS
    rights: ReadAndExecute
    type: allow
    state: present
    propagation: None
- name: Show installation flags
  ansible.builtin.debug:
    msg: '{{ win_install_args }}{% if datadog_windows_ddagentuser_password | default('''',
      true) | length > 0 %} DDAGENTUSER_PASSWORD=<REDACTED>{% endif %}'
- name: Set DD Password Arg
  when: datadog_windows_ddagentuser_password | default('', true) | length > 0
  ansible.builtin.set_fact:
    win_install_args: '{{ win_install_args }} DDAGENTUSER_PASSWORD={{ datadog_windows_ddagentuser_password
      }}'
- name: Install downloaded agent
  register: datadog_agent_install
  when: (not datadog_skip_install) and (not ansible_check_mode)
  ansible.windows.win_package:
    path: '{{ download_msi_result.dest }}'
    arguments: '{{ win_install_args }}'
- name: Delete temporary msi
  when: (not datadog_skip_install) and (not ansible_check_mode) and (download_msi_result.status_code
    == 200)
  ansible.windows.win_file:
    path: '{{ download_msi_result.dest }}'
    state: absent
