- name: Find out whether to set repo_gpgcheck or not
  ansible.builtin.set_fact:
    do_zypper_repo_gpgcheck: "{{ datadog_zypper_repo_gpgcheck if datadog_zypper_repo_gpgcheck\
      \ != '' else (\n  'yes' if datadog_zypper_repo == '' and datadog_agent_major_version|int\
      \ != 5 else 'no'\n) }}"
- block:
  - name: Stat if current RPM key already exists
    register: ddkeycurrent
    ansible.builtin.stat:
      path: /tmp/DATADOG_RPM_KEY_CURRENT.public
  - name: Download current RPM key (SLES11)
    when: not ddkeycurrent.stat.exists
    ansible.builtin.get_url:
      url: '{{ datadog_zypper_gpgkey_current }}'
      dest: /tmp/DATADOG_RPM_KEY_CURRENT.public
      force: true
  when: ansible_distribution_version|int == 11
- name: Download current RPM key
  when: ansible_distribution_version|int >= 12
  ansible.builtin.get_url:
    url: '{{ datadog_zypper_gpgkey_current }}'
    dest: /tmp/DATADOG_RPM_KEY_CURRENT.public
    force: true
- name: Import current RPM key
  when: not ansible_check_mode
  ansible.builtin.rpm_key:
    key: /tmp/DATADOG_RPM_KEY_CURRENT.public
    state: present
- block:
  - name: Stat if E09422B3 key (Expires 2022) RPM key already exists
    register: ddnewkey
    ansible.builtin.stat:
      path: /tmp/DATADOG_RPM_KEY_E09422B3.public
  - name: Download E09422B3 key (Expires 2022) RPM key (SLES11)
    when: not ddnewkey.stat.exists
    ansible.builtin.get_url:
      url: '{{ datadog_zypper_gpgkey_e09422b3 }}'
      dest: /tmp/DATADOG_RPM_KEY_E09422B3.public
  when: ansible_distribution_version|int == 11
- name: Download E09422B3 key (Expires 2022) RPM key
  when: ansible_distribution_version|int >= 12
  ansible.builtin.get_url:
    url: '{{ datadog_zypper_gpgkey_e09422b3 }}'
    dest: /tmp/DATADOG_RPM_KEY_E09422B3.public
    checksum: sha256:{{ datadog_zypper_gpgkey_e09422b3_sha256sum }}
- name: Import E09422B3 key (Expires 2022) RPM key
  when: not ansible_check_mode
  ansible.builtin.rpm_key:
    key: /tmp/DATADOG_RPM_KEY_E09422B3.public
    state: present
- block:
  - name: Stat if 20200908 key (Expires 2024) RPM key already exists
    register: ddnewkey_20200908
    ansible.builtin.stat:
      path: /tmp/DATADOG_RPM_KEY_20200908.public
  - name: Download 20200908 key (Expires 2024) RPM key (SLES11)
    when: not  ddnewkey_20200908.stat.exists
    ansible.builtin.get_url:
      url: '{{ datadog_zypper_gpgkey_20200908 }}'
      dest: /tmp/DATADOG_RPM_KEY_20200908.public
  when: ansible_distribution_version|int == 11
- name: Download 20200908 key (Expires 2024) RPM key
  when: ansible_distribution_version|int >= 12
  ansible.builtin.get_url:
    url: '{{ datadog_zypper_gpgkey_20200908 }}'
    dest: /tmp/DATADOG_RPM_KEY_20200908.public
    checksum: sha256:{{ datadog_zypper_gpgkey_20200908_sha256sum }}
- name: Import 20200908 key (Expires 2024) RPM key
  when: not ansible_check_mode
  ansible.builtin.rpm_key:
    key: /tmp/DATADOG_RPM_KEY_20200908.public
    state: present
- name: Install DataDog zypper repo
  register: datadog_zypper_repo_template
  when: datadog_manage_zypper_repofile
  ansible.builtin.template:
    src: zypper.repo.j2
    dest: /etc/zypp/repos.d/datadog.repo
    owner: root
    group: root
    mode: 420
- name: refresh Datadog zypper_repos
  when: datadog_zypper_repo_template.changed and not ansible_check_mode
  args:
    warn: false
  ansible.builtin.command: zypper refresh datadog
- when: datadog_agent_suse_version is defined
  ansible.builtin.include_tasks: pkg-suse/install-pinned.yml
- when: datadog_agent_suse_version is not defined
  ansible.builtin.include_tasks: pkg-suse/install-latest.yml
