---
- name: Install agent 7 macos
  hosts: all
  tasks:
    - name: Import role
      ansible.builtin.import_role:
        name: datadog.dd.agent
  vars:
    datadog_api_key: "11111111111111111111111111111111"
    datadog_enabled: false
    datadog_agent_major_version: 7
    datadog_config:
      tags: "mytag0, mytag1"
      log_level: INFO
      apm_enabled: "true" # has to be set as a string
    datadog_config_ex:
      trace.config:
        env: dev
      trace.concentrator:
        extra_aggregators: version
    runtime_security_config:
      enabled: true
    datadog_checks:
      process:
        init_config:
        instances:
          - name: agent
            search_string: ["agent", "sshd"]
