- name: Install pinned datadog-agent package
  register: datadog_agent_install
  when: not ansible_check_mode
  notify: restart datadog-agent
  community.general.zypper:
    name: datadog-agent={{ datadog_agent_suse_version }}
    state: present
    oldpackage: '{{ datadog_agent_allow_downgrade }}'
