- name: Install latest datadog-agent package
  register: datadog_agent_install
  when: not ansible_check_mode
  ansible.builtin.apt:
    name: '{{ datadog_agent_flavor }}'
    state: latest
    update_cache: true
    cache_valid_time: '{{ datadog_apt_cache_valid_time }}'
