name: ansible-tests
on:
  push:

jobs:
  ansible-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [debian]
        ansible_version: ["2_9", "2_10", "3_4", "4_10"]
        agent_version: ["5","6","7"]
    container:
      image: datadog/docker-library:ansible_${{ matrix.os }}_${{ matrix.ansible_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the Ansible collection
        run: ansible-galaxy collection build
      - name: Install the Ansible collection
        run: ansible-galaxy collection install datadog-dd-*.tar.gz
      

