name: Pull ansible-datadog

on: [workflow_dispatch]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
        with:
          repository: DataDog/ansible-datadog
          path: roles/agent
      - name: Edit install info file
        run: |
          sed -i "s/datadog_role/datadog_collection_agent_role/g" roles/agent/templates/install_info.j2
      - uses: stefanzweifel/git-auto-commit-action@v4
