name: Sync ansible-datadog role inside of roles/agent

on: [workflow_dispatch]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
        with:
          repository: DataDog/ansible-datadog
          path: roles/agent
      - name: Cleanup checked out repository
        run: |
          find roles/agent/ -not -path '*defaults*' -not -path '*tasks*' -not -path '*templates*' -not -name '.gitkeep' -type f -exec rm -r {} \;
          touch roles/agent/.gitkeep
      - name: Edit install info file
        run: |
          collection_version=$(cat galaxy.yml | grep "version:" | awk -F: '{print $2}' | xargs)
          sed -i "s/datadog_role/datadog_collection_${collection_version}_agent_role/g" roles/agent/templates/install_info.j2
      - uses: stefanzweifel/git-auto-commit-action@v4
