name: Pull ansible-datadog

on: [workflow_dispatch]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
        with:
          name: DataDog/ansible-datadog
          path: roles/agent
      - name: Edit install info file
        run: |
          ls roles/agent

            # - uses: stefanzweifel/git-auto-commit-action@v4
