name: unit-tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Check if collection version correctly matches install_info
              run: |
                galaxy_collection_version=$(cat galaxy.yml | grep "version:" | awk -F: '{print $2}' | xargs)
                install_info_collection_version=$(cat roles/agent/templates/install_info.j2| grep -o "datadog_collection_.*_agent_role" | awk -F_ '{ print $3 }')
                test "$galaxy_collection_version" = "$install_info_collection_version"
    sanity:
      uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
    all_green:
      needs:
        - sanity
      runs-on: ubuntu-latest
      steps:
        - run: |
            python -c "assert '${{ needs.sanity.result }}' == 'success'"
    ansible_lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Check ansible-datadog formatting
          run: |
            pip install -r requirements.txt
            ansible-lint -v --profile production
